[package]
name = "flamenco"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort" 

[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0"
volatile = "0.2.6"
